// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHqpk4Ax_V2iyPd1-O2dAuZAI6_firg8',
    appId: '1:867906611234:web:d819902d14646d2f73027b',
    messagingSenderId: '867906611234',
    projectId: 'kolot-8fb44',
    authDomain: 'kolot-8fb44.firebaseapp.com',
    storageBucket: 'kolot-8fb44.appspot.com',
    measurementId: 'G-33BWXJBJ9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhD9pqBYJCk2P5rukBDN1mQcWg1HQvl0s',
    appId: '1:867906611234:android:12debc471f6cb83c73027b',
    messagingSenderId: '867906611234',
    projectId: 'kolot-8fb44',
    storageBucket: 'kolot-8fb44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeQdZ7GF9qwv8IbsFA5qHL6z0pE7lGj70',
    appId: '1:867906611234:ios:7695edddcd5e26dc73027b',
    messagingSenderId: '867906611234',
    projectId: 'kolot-8fb44',
    storageBucket: 'kolot-8fb44.appspot.com',
    iosClientId: '867906611234-b3j7l0n94trn97qd9fgjr1fqmk0a6cr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kolot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeQdZ7GF9qwv8IbsFA5qHL6z0pE7lGj70',
    appId: '1:867906611234:ios:965b43e839a639bd73027b',
    messagingSenderId: '867906611234',
    projectId: 'kolot-8fb44',
    storageBucket: 'kolot-8fb44.appspot.com',
    iosClientId: '867906611234-f5kddhaa5dvb1uti14vknu1ek7vqm0l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.kolot.RunnerTests',
  );
}
